/**
 * India Delivery Challan Register — Google Apps Script v2
 * 
 * Supports dual series:
 *   DC = Delivery Challan (outbound)
 *   RC = Return Challan (inbound)
 *
 * Deploy as Web App:
 *   1. Open this script in Apps Script editor
 *   2. Click Deploy → New Deployment
 *   3. Type: Web App
 *   4. Execute as: Me
 *   5. Who has access: Anyone
 *   6. Deploy → copy the URL
 *   7. Paste the URL into the challan app config
 *
 * ENDPOINTS:
 *   GET  ?action=next&prefix=DC     → Returns next delivery challan number
 *   GET  ?action=next&prefix=RC     → Returns next return challan number
 *   GET  ?action=check&orderRef=xxx → Check if order already has a challan
 *   POST {action:"register", prefix:"DC"|"RC", ...} → Register and get number
 */

// ─── CONFIG ───
const SHEET_NAME = "Register";
const COUNTER_SHEET = "Counter";
const VALID_PREFIXES = ["DC", "RC"];

// ─── HELPERS ───
function getFinancialYear() {
  const now = new Date();
  const year = now.getFullYear();
  const month = now.getMonth(); // 0-indexed
  const fyStart = month >= 3 ? year : year - 1;
  const fyEnd = fyStart + 1;
  return `${String(fyStart).slice(2)}${String(fyEnd).slice(2)}`;
}

function formatChallanNumber(prefix, fy, seq) {
  // DC2526000001 or RC2526000001 (12 chars, under 16-char GST limit)
  return `${prefix}${fy}${String(seq).padStart(6, "0")}`;
}

function validatePrefix(prefix) {
  prefix = String(prefix || "DC").toUpperCase();
  return VALID_PREFIXES.includes(prefix) ? prefix : "DC";
}

function getOrCreateSheet(ss, name, headers) {
  let sheet = ss.getSheetByName(name);
  if (!sheet) {
    sheet = ss.insertSheet(name);
    if (headers) {
      sheet.getRange(1, 1, 1, headers.length).setValues([headers]);
      sheet.getRange(1, 1, 1, headers.length).setFontWeight("bold");
      sheet.setFrozenRows(1);
    }
  }
  return sheet;
}

// ─── NEXT NUMBER (peek, no increment) ───
function getNextNumber(prefix) {
  prefix = validatePrefix(prefix);
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  const fy = getFinancialYear();
  const counterSheet = getOrCreateSheet(ss, COUNTER_SHEET, ["Prefix", "FinancialYear", "LastNumber", "UpdatedAt"]);
  
  const data = counterSheet.getDataRange().getValues();
  let fyRow = -1;
  for (let i = 1; i < data.length; i++) {
    if (String(data[i][0]) === prefix && String(data[i][1]) === fy) { fyRow = i + 1; break; }
  }
  
  if (fyRow === -1) {
    // New prefix+FY combo — start at 0 (will become 1 on first register)
    const newRow = data.length + 1;
    counterSheet.getRange(newRow, 1, 1, 4).setValues([[prefix, fy, 0, new Date()]]);
    return { prefix, fy, next: 1, challanNumber: formatChallanNumber(prefix, fy, 1) };
  }
  
  const lastNum = Number(data[fyRow - 1][2]) || 0;
  return { prefix, fy, next: lastNum + 1, challanNumber: formatChallanNumber(prefix, fy, lastNum + 1) };
}

function incrementCounter(prefix, fy) {
  prefix = validatePrefix(prefix);
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  const counterSheet = ss.getSheetByName(COUNTER_SHEET);
  const data = counterSheet.getDataRange().getValues();
  
  for (let i = 1; i < data.length; i++) {
    if (String(data[i][0]) === prefix && String(data[i][1]) === fy) {
      const newNum = Number(data[i][2]) + 1;
      counterSheet.getRange(i + 1, 3).setValue(newNum);
      counterSheet.getRange(i + 1, 4).setValue(new Date());
      return newNum;
    }
  }
  
  // Prefix+FY not found — create it at 1
  const newRow = data.length + 1;
  counterSheet.getRange(newRow, 1, 1, 4).setValues([[prefix, fy, 1, new Date()]]);
  return 1;
}

// ─── REGISTER A CHALLAN ───
function registerChallan(payload) {
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  const fy = getFinancialYear();
  const prefix = validatePrefix(payload.prefix);
  
  const registerHeaders = [
    "Challan No", "Date", "Financial Year", "Type",
    "Order Reference", "Customer (Owner)", 
    "Consignee Name", "Consignee City", "Consignee State",
    "Delivery Type", "Direction",
    "Items Count", "Items Description",
    "Total Declared Value", "Condition",
    "Transporter", "AWB No", "e-Way Bill",
    "Dispatch From",
    "Generated By", "Status", "Timestamp"
  ];
  
  const registerSheet = getOrCreateSheet(ss, SHEET_NAME, registerHeaders);
  
  // Lock to prevent race conditions
  const lock = LockService.getScriptLock();
  lock.waitLock(10000);
  
  try {
    const seq = incrementCounter(prefix, fy);
    const challanNumber = formatChallanNumber(prefix, fy, seq);
    
    const row = [
      challanNumber,
      payload.date || new Date().toLocaleDateString("en-IN"),
      `20${fy.slice(0,2)}-${fy.slice(2,4)}`,
      prefix === "RC" ? "Return" : "Delivery",
      payload.orderRef || "",
      payload.owner || "",
      payload.consigneeName || "",
      payload.consigneeCity || "",
      payload.consigneeState || "",
      payload.deliveryType || "residence",
      payload.direction || (prefix === "RC" ? "inbound" : "outbound"),
      payload.itemsCount || 0,
      payload.itemsDescription || "",
      payload.totalValue || 0,
      payload.condition || "",
      payload.transporter || "",
      payload.awbNumber || "",
      payload.ewayBill || "",
      payload.dispatchFrom || "",
      payload.generatedBy || "",
      "Generated",
      new Date()
    ];
    
    registerSheet.appendRow(row);
    
    return {
      success: true,
      challanNumber: challanNumber,
      sequence: seq,
      prefix: prefix,
      type: prefix === "RC" ? "Return" : "Delivery",
      financialYear: `20${fy.slice(0,2)}-${fy.slice(2,4)}`,
      row: registerSheet.getLastRow()
    };
  } finally {
    lock.releaseLock();
  }
}

// ─── CHECK IF ORDER ALREADY HAS CHALLAN ───
function checkOrder(orderRef) {
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  const sheet = ss.getSheetByName(SHEET_NAME);
  if (!sheet) return { exists: false };
  
  const data = sheet.getDataRange().getValues();
  const headers = data[0];
  const refCol = headers.indexOf("Order Reference");
  const challanCol = headers.indexOf("Challan No");
  const statusCol = headers.indexOf("Status");
  const typeCol = headers.indexOf("Type");
  
  const matches = [];
  for (let i = 1; i < data.length; i++) {
    if (String(data[i][refCol]) === String(orderRef) && String(data[i][statusCol]) !== "Voided") {
      matches.push({ challanNumber: data[i][challanCol], status: data[i][statusCol], type: data[i][typeCol] });
    }
  }
  
  if (matches.length === 0) return { exists: false };
  return { exists: true, matches: matches, challanNumber: matches[0].challanNumber };
}

// ─── WEB APP HANDLERS ───
function doGet(e) {
  const action = (e.parameter && e.parameter.action) || "next";
  const prefix = (e.parameter && e.parameter.prefix) || "DC";
  let result;
  
  if (action === "next") {
    result = getNextNumber(prefix);
  } else if (action === "check" && e.parameter.orderRef) {
    result = checkOrder(e.parameter.orderRef);
  } else {
    result = { error: "Unknown action. Use ?action=next&prefix=DC or ?action=check&orderRef=..." };
  }
  
  return ContentService
    .createTextOutput(JSON.stringify(result))
    .setMimeType(ContentService.MimeType.JSON);
}

function doPost(e) {
  let payload;
  try {
    payload = JSON.parse(e.postData.contents);
  } catch (err) {
    return ContentService
      .createTextOutput(JSON.stringify({ error: "Invalid JSON payload" }))
      .setMimeType(ContentService.MimeType.JSON);
  }
  
  const action = payload.action || "register";
  let result;
  
  if (action === "register") {
    result = registerChallan(payload);
  } else if (action === "check") {
    result = checkOrder(payload.orderRef);
  } else {
    result = { error: "Unknown action. Use action: 'register' or 'check'" };
  }
  
  return ContentService
    .createTextOutput(JSON.stringify(result))
    .setMimeType(ContentService.MimeType.JSON);
}
